### PR TITLE
Limit Jar network to pairs only

### PR DESCRIPTION
**Pull request by DrParadox7**
Refactored Mirrored Jars.
Jar Network capacity is now capped at 2, to trade only in pairs, significantly improving performance. 
These jars will function exactly as expected as TC4 mirrors can only be paired.

It's important to note that this PR is a nerf, as Mirrored Jars Networks currently can hold infinite Mirrored Jars which will degrade performance massively relative to the network's size.

The existing mechanism continuously sorts an ArrayList of all jars to find those with the most and least essentia. 
After transferring 1 Essentia, it restarts the entire process, causing substantial lag and being terribly inefficiency.

__Fixes:__
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8724

Extra: Jar labels are no longer lost on placement.

__Fixes:__
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/4942 (It wasn't fixed)

### CODE REVIEW

**Comment by DrParadox7** [comment]
This gives a good overview:
https://spark.lucko.me/28gR5JOODu

That's a single player using them excessively in their setup

**Comment by Alastors** [comment]
I object to this PR, I get what you’re trying to do, but if performance is the issue, we need to look into the specifics of why, instead of massive nerfs that just crutch the issue.

**Comment by Glease** [comment]
~~at first glance the thing tick the same network multiple time per tick (time equal to the number of connected jars). we can reduce cpu time to 1/10000 if one network is ticked only once per tick instead of once per tick per jar~~

EDIT: no it doesn't, but if sorting is the problem maybe try a sorted collection. I'd assume the network rarely updates so it doesn't need to be sorted once per tick

**Comment by DrParadox7** [comment]
> I object to this PR, I get what you’re trying to do, but if performance is the issue, we need to look into the specifics of why, instead of massive nerfs that just crutch the issue.

Sorting the list keeps the level of all jars equal. This is a cause of a major TPS lag. My rework gets rid of it without losing its main functionality (which stays true to the original concept as mirrors work in pairs).

The fix already benefits its intended playerbase so whether the GTNH team adopts it or not is of no relevance to me.

I won't volunteer my time and lose myself in a process that does not benefit me but hope my PR inspires you to take matters on to your own hand.
As the saying goes:
> "If you want something done right, do it yourself"

**Comment by DrParadox7** [comment]
@serenibyss You might want to include the label fix from the first commit as well to ensure nothing minor but worthwhile is overlooked from superseding this PR:
> Also fixes Jar labels being lost on placement
https://github.com/DrParadox7/Gadomancy/blob/fb5bf61efd9ba0a55fe480aa2fee5e7a425ff6a8/src/main/java/makeo/gadomancy/common/items/ItemBlockRemoteJar.java#L133

**Pull request closed without merging**
